"""
Emit IEEE-format LaTeX tables (T1-T3) from the measured results.

Every number here was produced by a script in this directory; the source is
named in the comment beside each row so any value can be traced and re-run.
Written to ../figures/tables.tex for direct \\input{} into the report.
"""

import os

OUT = "../figures"
os.makedirs(OUT, exist_ok=True)

# ---------------------------------------------------------------- T1
# sources: test_fold.py, validate_beam.py, model2dof.py,
#          validate_nazemi.py, validate_mtest.py
T1 = r"""
\begin{table}[t]
\caption{Solver validation against independent published sources.
Errors are relative unless noted. ``mech.'' denotes the predicted
instability mechanism.}
\label{tab:validation}
\centering\footnotesize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}llrrr@{}}
\toprule
Source & Quantity & Ours & Published & Error \\
\midrule
Flores; Gomez \textit{et al.} & $\lambda^*$ (lumped)      & 0.148150 & 0.148148 & 0.001\% \\
Standard $\Lambda_{\rm PI}$   & cantilever                & 1.6799   & 1.6790   & 0.05\%  \\
Standard $\Lambda_{\rm PI}$   & fixed--fixed              & 69.935   & 71.167   & 1.73\%  \\
Analytic $c^3$ law            & $\sum \partial\Lambda/\partial D$ & 5.0398 & 5.0398 & 0.00\% \\
Seeger \& Boser, Tab.~I       & tip-in, design \#1        & 19.0\%   & 19\%     & --- \\
Seeger \& Boser, Tab.~I       & tip-in, design \#3        & 85.1\%   & 85\%     & --- \\
Seeger \& Boser, Tab.~III     & mech., 3 designs          & 3/3      & 3/3      & --- \\
Nazemi \textit{et al.} 2025   & $V_{\rm PI}$ reduction    & 13.2\%   & 16.0\%   & 2.8\,pp \\
M-TEST (\emph{measured})      & $V_{\rm PI}$, 500\,\textmu m FB & 11.70\,V & 11.1$\pm$0.1\,V & +5.4\% \\
\bottomrule
\end{tabular}
\end{table}
"""

# ---------------------------------------------------------------- T2
# source: inverse_design.py (both boundary conditions, N=60)
T2 = r"""
\begin{table}[t]
\caption{Inverse design versus the published hand-tuned study
(Haluzan \textit{et al.}), both boundary conditions, all designs re-fitted to
2\,\textmu m stable travel. The optimal exponent \emph{reverses} between the
two cases, which our solver reproduces.}
\label{tab:inverse}
\centering\footnotesize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}lrrrr@{}}
\toprule
& \multicolumn{2}{c}{Cantilever} & \multicolumn{2}{c}{Fixed--fixed} \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}
Design & Ours & Paper & Ours & Paper \\
\midrule
Uniform gap            & 22.86 & 23.66 & 175.83 & 178.26 \\
Linear ($n{=}1$)       & 14.31 & 14.86 & 123.01 & 125.48 \\
Best published family  & 13.61 & 14.14 & 121.79 & 123.94 \\
Free-form (ours)       & \textbf{13.60} & --- & \textbf{120.03} & --- \\
\midrule
Optimal exponent $n^*$ & 1.29 & 4/3 & 1.00 & 1.00 \\
Gain over best family  & 0.14\% & --- & 1.45\% & --- \\
\bottomrule
\end{tabular}
\end{table}
"""

# ---------------------------------------------------------------- T3
# sources: surrogate_fair.py, fno_surrogate.py, amortized_hard.py,
#          amortized_vs_converged.py
T3 = r"""
\begin{table}[t]
\caption{Design methods on the same task (cantilever, 2\,\textmu m travel).
Surrogate and direct rows share an equal budget of 400 true fold solves;
all designs are scored at exactly 2\,\textmu m travel by the exact solver.}
\label{tab:methods}
\centering\footnotesize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}lrrr@{}}
\toprule
Method & $V_{\rm PI}$ [V] & Train. samples & Design time \\
\midrule
MLP surrogate + active learning & 17.203 & 400 & 71\,s \\
FNO surrogate + active learning & 14.245 & 400 & 594\,s \\
Direct differentiable (400)     & 13.783 & 0   & 15\,s \\
Direct, converged (4 restarts)  & 13.665 & 0   & 170\,s \\
Amortized network               & 13.636 & \textbf{0} & \textbf{0.04\,ms} \\
Network $+$ 100 steps           & \textbf{13.599} & 0 & 17\,s \\
\midrule
\multicolumn{4}{@{}l@{}}{\footnotesize Hand-tuned published design: 14.14\,V.
Network training: 1577\,s, 6000 live solves, 0 stored.} \\
\bottomrule
\end{tabular}
\end{table}
"""

if __name__ == "__main__":
    with open(f"{OUT}/tables.tex", "w") as f:
        f.write("% Auto-generated by sim/make_tables.py -- do not edit by hand.\n")
        f.write("% Requires: \\usepackage{booktabs}\n")
        for t in (T1, T2, T3):
            f.write(t)
            f.write("\n")
    print(f"wrote {OUT}/tables.tex")
    for name, t in [("T1 validation", T1), ("T2 inverse design", T2),
                    ("T3 methods", T3)]:
        rows = [l for l in t.splitlines()
                if "&" in l and "multicolumn" not in l and "cmidrule" not in l]
        print(f"  {name}: {len(rows)} rows")
